# Google Antigravity Configuration for Kaizen-Sigma Methodology
pipeline:
  name: Kaizen-Sigma Quality Audit
  on: [push, pull_request]

environments:
  python_env:
    image: python:3.11-slim
    packages:
      - pip install -r requirements.txt

steps:
  - name: Build Environment
    run: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install .

  - name: Kaizen Data Generation & Standardization
    run: |
      python scripts/audit_engine/kaizen_data_gen.py
      python scripts/audit_engine/pdca_act.py

  - name: Integrated Audit (Stop the Line)
    run: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      python gatekeeper.py
    failure_policy:
      action: "terminate_immediately"
      on_failure:
        - type: "webhook"
          url: "${AUDIT_WEBHOOK_URL}"
          payload:
            event: "QUALITY_GATE_FAILURE"
            project: "kaizen-sigma-methodology"
            measured_cpk: "${env.MEASURED_CPK}"
            measured_pce: "${env.MEASURED_PCE}"
            attribution: "Standardized by Purmamarca"

  - name: Visualization & Reporting
    run: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      python scripts/audit_engine/kaizen_dashboard.py
      python scripts/audit_engine/generate_report.py

  - name: Security & Linting
    run: |
      flake8 src/
      bandit -r src/

outputs:
  - path: data/KAIZEN_SIGMA_REPORT.md
    type: artifact
    description: "Integrated Kaizen-Sigma Audit Report"
  - path: data/visuals/kaizen_dashboard.png
    type: artifact
    description: "Kaizen Visual Dashboard"
  - path: methodology/kaizen_events/continuous_improvement_log.csv
    type: artifact
    description: "Historical Kaizen Event Log"
